/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grocerypos;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Charles Andrei
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        POSButton = new javax.swing.JButton();
        IMSButton = new javax.swing.JButton();
        ADMButton = new javax.swing.JButton();
        SETButton = new javax.swing.JButton();
        MenuPanels = new javax.swing.JLayeredPane();
        POS = new javax.swing.JPanel();
        jSnacks = new javax.swing.JButton();
        jDrink = new javax.swing.JButton();
        jHouseUtensils = new javax.swing.JButton();
        jBabyNeeds = new javax.swing.JButton();
        ProductPanels = new javax.swing.JLayeredPane();
        SnacksScroll = new javax.swing.JScrollPane();
        SnacksPage = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        DrinksScroll = new javax.swing.JScrollPane();
        DrinksPage = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        HouseUtensilsScroll = new javax.swing.JScrollPane();
        HouseUtensilsPage = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        BabyNeedsScroll = new javax.swing.JScrollPane();
        BabyNeedsPage = new javax.swing.JPanel();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        IMS = new javax.swing.JPanel();
        ADM = new javax.swing.JPanel();
        SET = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\logo_sym (4).png")); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 153, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");

        jLabel3.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BIG BITE STORE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(348, 348, 348)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(522, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        POSButton.setBackground(new java.awt.Color(204, 204, 204));
        POSButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\si_Wallet_detailed (3).png")); // NOI18N
        POSButton.setText("POS");
        POSButton.setBorder(null);
        POSButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        POSButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        POSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POSButtonActionPerformed(evt);
            }
        });

        IMSButton.setText("IMS");
        IMSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMSButtonActionPerformed(evt);
            }
        });

        ADMButton.setText("ADM");
        ADMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADMButtonActionPerformed(evt);
            }
        });

        SETButton.setText("SET");
        SETButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SETButtonActionPerformed(evt);
            }
        });

        MenuPanels.setLayout(new java.awt.CardLayout());

        POS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSnacks.setBackground(new java.awt.Color(255, 102, 0));
        jSnacks.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jSnacks.setText("Snacks");
        jSnacks.setMaximumSize(new java.awt.Dimension(112, 36));
        jSnacks.setMinimumSize(new java.awt.Dimension(112, 36));
        jSnacks.setPreferredSize(new java.awt.Dimension(112, 36));
        jSnacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSnacksActionPerformed(evt);
            }
        });

        jDrink.setBackground(new java.awt.Color(255, 102, 0));
        jDrink.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jDrink.setText("Drinks");
        jDrink.setMaximumSize(new java.awt.Dimension(112, 36));
        jDrink.setMinimumSize(new java.awt.Dimension(112, 36));
        jDrink.setPreferredSize(new java.awt.Dimension(112, 36));
        jDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDrinkActionPerformed(evt);
            }
        });

        jHouseUtensils.setBackground(new java.awt.Color(255, 102, 0));
        jHouseUtensils.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jHouseUtensils.setText("House Utensils");
        jHouseUtensils.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHouseUtensilsActionPerformed(evt);
            }
        });

        jBabyNeeds.setBackground(new java.awt.Color(255, 102, 0));
        jBabyNeeds.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jBabyNeeds.setText("Baby Needs");
        jBabyNeeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBabyNeedsActionPerformed(evt);
            }
        });

        ProductPanels.setLayout(new java.awt.CardLayout());

        SnacksScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        SnacksScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        SnacksPage.setBackground(new java.awt.Color(153, 153, 153));

        jButton9.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nova.png"))); // NOI18N
        jButton9.setText("NOVA");
        jButton9.setBorder(null);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton10.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vcut.png"))); // NOI18N
        jButton10.setText("V-CUT");
        jButton10.setBorder(null);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton10.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton10.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/piattos.png"))); // NOI18N
        jButton2.setText("PIATTOS");
        jButton2.setBorder(null);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pillows.png"))); // NOI18N
        jButton3.setText("PILLOWS");
        jButton3.setBorder(null);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton3.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton3.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lays.png"))); // NOI18N
        jButton4.setText("LAYS");
        jButton4.setBorder(null);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton4.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton4.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cheetos.png"))); // NOI18N
        jButton5.setText("CHEETOS");
        jButton5.setBorder(null);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton5.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton5.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton6.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sweetcorn.png"))); // NOI18N
        jButton6.setText("SWEET CORN");
        jButton6.setBorder(null);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton6.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton7.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tomi.png"))); // NOI18N
        jButton7.setText("TOMI");
        jButton7.setBorder(null);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton7.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton7.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton8.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton8.setText("NAGARAYA");
        jButton8.setBorder(null);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton8.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton8.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton11.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\dingdong.png")); // NOI18N
        jButton11.setText("DING DONG");
        jButton11.setBorder(null);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton11.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton11.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton12.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\boybawang.png")); // NOI18N
        jButton12.setText("BOY BAWANG");
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton12.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton12.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton13.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\image 7 (3) (1).png")); // NOI18N
        jButton13.setText("CRACKLINGS");
        jButton13.setBorder(null);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton13.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton13.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout SnacksPageLayout = new javax.swing.GroupLayout(SnacksPage);
        SnacksPage.setLayout(SnacksPageLayout);
        SnacksPageLayout.setHorizontalGroup(
            SnacksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SnacksPageLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(SnacksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SnacksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SnacksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SnacksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        SnacksPageLayout.setVerticalGroup(
            SnacksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SnacksPageLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(SnacksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SnacksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SnacksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SnacksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        SnacksScroll.setViewportView(SnacksPage);

        ProductPanels.add(SnacksScroll, "card2");

        DrinksScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        DrinksScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        DrinksPage.setBackground(new java.awt.Color(153, 153, 153));

        jButton14.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\monster.png")); // NOI18N
        jButton14.setText("MONSTER");
        jButton14.setBorder(null);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton14.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton14.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton15.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\bang.png")); // NOI18N
        jButton15.setText("BANG");
        jButton15.setBorder(null);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton15.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton15.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton16.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\pocarisweat.png")); // NOI18N
        jButton16.setText("POCARI SWEAT");
        jButton16.setBorder(null);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton16.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton16.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton17.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\royal.png")); // NOI18N
        jButton17.setText("ROYAL");
        jButton17.setBorder(null);
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton17.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton17.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton17.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton18.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\sprite.png")); // NOI18N
        jButton18.setText("SPRITE");
        jButton18.setBorder(null);
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton18.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton18.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton18.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton19.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\tropicana.png")); // NOI18N
        jButton19.setText("TROPICANA");
        jButton19.setBorder(null);
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton19.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton19.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton19.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton20.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\smartc.png")); // NOI18N
        jButton20.setText("SMART - C");
        jButton20.setBorder(null);
        jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton20.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton20.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton20.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton21.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\minutemaid.png")); // NOI18N
        jButton21.setText("MINUTE MAID");
        jButton21.setBorder(null);
        jButton21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton21.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton21.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton21.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton21.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout DrinksPageLayout = new javax.swing.GroupLayout(DrinksPage);
        DrinksPage.setLayout(DrinksPageLayout);
        DrinksPageLayout.setHorizontalGroup(
            DrinksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrinksPageLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(DrinksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DrinksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DrinksPageLayout.createSequentialGroup()
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DrinksPageLayout.createSequentialGroup()
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        DrinksPageLayout.setVerticalGroup(
            DrinksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrinksPageLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(DrinksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DrinksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        DrinksScroll.setViewportView(DrinksPage);

        ProductPanels.add(DrinksScroll, "card3");

        HouseUtensilsScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        HouseUtensilsScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        HouseUtensilsPage.setBackground(new java.awt.Color(153, 153, 153));

        jButton22.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton22.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\airpurifier.png")); // NOI18N
        jButton22.setText("AIR PURIFIER");
        jButton22.setBorder(null);
        jButton22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton22.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton22.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton22.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton22.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton23.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton23.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\mop.png")); // NOI18N
        jButton23.setText("MOP");
        jButton23.setBorder(null);
        jButton23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton23.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton23.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton23.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton24.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton24.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\casserole.png")); // NOI18N
        jButton24.setText("CASSEROLE");
        jButton24.setBorder(null);
        jButton24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton24.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton24.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton24.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton24.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton25.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton25.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\potbundle.png")); // NOI18N
        jButton25.setText("POT BUNDLE");
        jButton25.setBorder(null);
        jButton25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton25.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton25.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton25.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton25.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton26.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton26.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\dishwashingliquid.png")); // NOI18N
        jButton26.setText("DISHWASHING LIQUID");
        jButton26.setBorder(null);
        jButton26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton26.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton26.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton26.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton26.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton27.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton27.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\cuttingboard.png")); // NOI18N
        jButton27.setText("CUTTING BOARD");
        jButton27.setBorder(null);
        jButton27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton27.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton27.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton27.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton27.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton28.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton28.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\scrub.png")); // NOI18N
        jButton28.setText("SCRUB");
        jButton28.setBorder(null);
        jButton28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton28.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton28.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton28.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton28.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton29.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton29.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\carpet.png")); // NOI18N
        jButton29.setText("CARPET");
        jButton29.setBorder(null);
        jButton29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton29.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton29.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton29.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton29.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton30.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton30.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\containers.png")); // NOI18N
        jButton30.setText("CONTAINERS");
        jButton30.setBorder(null);
        jButton30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton30.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton30.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton30.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton30.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton31.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton31.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\tissue.png")); // NOI18N
        jButton31.setText("TISSUE");
        jButton31.setBorder(null);
        jButton31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton31.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton31.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton31.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton31.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton32.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton32.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\hanger.png")); // NOI18N
        jButton32.setText("HANGER");
        jButton32.setBorder(null);
        jButton32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton32.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton32.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton32.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton32.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton33.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton33.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\knives.png")); // NOI18N
        jButton33.setText("KNIVES");
        jButton33.setBorder(null);
        jButton33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton33.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton33.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton33.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton33.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout HouseUtensilsPageLayout = new javax.swing.GroupLayout(HouseUtensilsPage);
        HouseUtensilsPage.setLayout(HouseUtensilsPageLayout);
        HouseUtensilsPageLayout.setHorizontalGroup(
            HouseUtensilsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HouseUtensilsPageLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(HouseUtensilsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HouseUtensilsPageLayout.createSequentialGroup()
                        .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HouseUtensilsPageLayout.createSequentialGroup()
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HouseUtensilsPageLayout.createSequentialGroup()
                        .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        HouseUtensilsPageLayout.setVerticalGroup(
            HouseUtensilsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HouseUtensilsPageLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(HouseUtensilsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HouseUtensilsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HouseUtensilsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        HouseUtensilsScroll.setViewportView(HouseUtensilsPage);

        ProductPanels.add(HouseUtensilsScroll, "card4");

        BabyNeedsScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        BabyNeedsScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        BabyNeedsPage.setBackground(new java.awt.Color(153, 153, 153));

        jButton34.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton34.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\babysocks.png")); // NOI18N
        jButton34.setText("BABY SOCKS");
        jButton34.setBorder(null);
        jButton34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton34.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton34.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton34.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton34.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton35.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton35.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\babyshoes.png")); // NOI18N
        jButton35.setText("BABY SHOES");
        jButton35.setBorder(null);
        jButton35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton35.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton35.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton35.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton35.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton46.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton46.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\babystroller.png")); // NOI18N
        jButton46.setText("BABY STROLLER");
        jButton46.setBorder(null);
        jButton46.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton46.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton46.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton46.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton46.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton47.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton47.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\babycrib.png")); // NOI18N
        jButton47.setText("BABY CRIB");
        jButton47.setBorder(null);
        jButton47.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton47.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton47.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton47.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton47.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton48.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton48.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\babysoap.png")); // NOI18N
        jButton48.setText("BABY SOAP");
        jButton48.setAutoscrolls(true);
        jButton48.setBorder(null);
        jButton48.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton48.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton48.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton48.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton48.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton49.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton49.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\babyclothes.png")); // NOI18N
        jButton49.setText("BABY CLOTHES");
        jButton49.setAutoscrolls(true);
        jButton49.setBorder(null);
        jButton49.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton49.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton49.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton49.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton49.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton50.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton50.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\babybottles.png")); // NOI18N
        jButton50.setText("BABY BOTTLE");
        jButton50.setAutoscrolls(true);
        jButton50.setBorder(null);
        jButton50.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton50.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton50.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton50.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton50.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton51.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton51.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\babyteether.png")); // NOI18N
        jButton51.setText("BABY TEETHER");
        jButton51.setAutoscrolls(true);
        jButton51.setBorder(null);
        jButton51.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton51.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton51.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton51.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton51.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton52.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton52.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\babydiapers.png")); // NOI18N
        jButton52.setText("BABY DIAPERS");
        jButton52.setAutoscrolls(true);
        jButton52.setBorder(null);
        jButton52.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton52.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton52.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton52.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton52.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton53.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton53.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\babyspoon.png")); // NOI18N
        jButton53.setText("BABY SPOON");
        jButton53.setAutoscrolls(true);
        jButton53.setBorder(null);
        jButton53.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton53.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton53.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton53.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton53.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton55.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton55.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\babymilk.png")); // NOI18N
        jButton55.setText("BABY MILK");
        jButton55.setAutoscrolls(true);
        jButton55.setBorder(null);
        jButton55.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton55.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton55.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton55.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton55.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton56.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton56.setIcon(new javax.swing.ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\babytoy.png")); // NOI18N
        jButton56.setText("BABY TOY");
        jButton56.setAutoscrolls(true);
        jButton56.setBorder(null);
        jButton56.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton56.setMaximumSize(new java.awt.Dimension(180, 186));
        jButton56.setMinimumSize(new java.awt.Dimension(180, 186));
        jButton56.setPreferredSize(new java.awt.Dimension(180, 186));
        jButton56.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout BabyNeedsPageLayout = new javax.swing.GroupLayout(BabyNeedsPage);
        BabyNeedsPage.setLayout(BabyNeedsPageLayout);
        BabyNeedsPageLayout.setHorizontalGroup(
            BabyNeedsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BabyNeedsPageLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(BabyNeedsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton52, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BabyNeedsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BabyNeedsPageLayout.createSequentialGroup()
                        .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BabyNeedsPageLayout.createSequentialGroup()
                        .addComponent(jButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton51, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BabyNeedsPageLayout.createSequentialGroup()
                        .addComponent(jButton53, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton55, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton56, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        BabyNeedsPageLayout.setVerticalGroup(
            BabyNeedsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BabyNeedsPageLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(BabyNeedsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BabyNeedsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton49, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton51, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BabyNeedsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton55, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton53, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton52, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton56, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        BabyNeedsScroll.setViewportView(BabyNeedsPage);

        ProductPanels.add(BabyNeedsScroll, "card5");

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        jLayeredPane1.add(jPanel1, "card2");

        javax.swing.GroupLayout POSLayout = new javax.swing.GroupLayout(POS);
        POS.setLayout(POSLayout);
        POSLayout.setHorizontalGroup(
            POSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(POSLayout.createSequentialGroup()
                .addGroup(POSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(POSLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jSnacks, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jHouseUtensils, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBabyNeeds, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(POSLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(ProductPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        POSLayout.setVerticalGroup(
            POSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(POSLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(POSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(POSLayout.createSequentialGroup()
                        .addGroup(POSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSnacks, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jHouseUtensils, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBabyNeeds, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProductPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jLayeredPane1))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        MenuPanels.add(POS, "card2");

        IMS.setBackground(new java.awt.Color(255, 102, 102));
        IMS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout IMSLayout = new javax.swing.GroupLayout(IMS);
        IMS.setLayout(IMSLayout);
        IMSLayout.setHorizontalGroup(
            IMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1213, Short.MAX_VALUE)
        );
        IMSLayout.setVerticalGroup(
            IMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        MenuPanels.add(IMS, "card3");

        ADM.setBackground(new java.awt.Color(255, 255, 0));
        ADM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout ADMLayout = new javax.swing.GroupLayout(ADM);
        ADM.setLayout(ADMLayout);
        ADMLayout.setHorizontalGroup(
            ADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1213, Short.MAX_VALUE)
        );
        ADMLayout.setVerticalGroup(
            ADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        MenuPanels.add(ADM, "card4");

        SET.setBackground(new java.awt.Color(0, 0, 153));
        SET.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout SETLayout = new javax.swing.GroupLayout(SET);
        SET.setLayout(SETLayout);
        SETLayout.setHorizontalGroup(
            SETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1213, Short.MAX_VALUE)
        );
        SETLayout.setVerticalGroup(
            SETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        MenuPanels.add(SET, "card5");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(SETButton))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ADMButton))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IMSButton))
                    .addComponent(POSButton))
                .addGap(31, 31, 31)
                .addComponent(MenuPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 1215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addComponent(POSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IMSButton)
                        .addGap(74, 74, 74)
                        .addComponent(ADMButton)
                        .addGap(36, 36, 36)
                        .addComponent(SETButton)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addComponent(MenuPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void POSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POSButtonActionPerformed
        POS.setVisible(true);
        IMS.setVisible(false);
        ADM.setVisible(false);
        SET.setVisible(false);
        ImageIcon icon = new ImageIcon("C:\\Users\\Charles Andrei\\Downloads\\pos.png");
        POSButton.setIcon(icon);
        POSButton.setBackground(Color.green);
        POSButton.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_POSButtonActionPerformed

    private void jBabyNeedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBabyNeedsActionPerformed
        
        SnacksScroll.setVisible(false);
        DrinksScroll.setVisible(false);
        HouseUtensilsScroll.setVisible(false);
        BabyNeedsScroll.setVisible(true);
        jBabyNeeds.setBackground(new java.awt.Color(0, 153, 102));
        jDrink.setBackground(new java.awt.Color(255, 102, 0));
        jSnacks.setBackground(new java.awt.Color(255, 102, 0));
        jHouseUtensils.setBackground(new java.awt.Color(255, 102, 0));
        
        jBabyNeeds.setForeground(Color.WHITE);
        jDrink.setForeground(Color.BLACK);
        jSnacks.setForeground(Color.BLACK);
        jHouseUtensils.setForeground(Color.BLACK);
    }//GEN-LAST:event_jBabyNeedsActionPerformed

    private void jDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDrinkActionPerformed
        SnacksScroll.setVisible(false);
        DrinksScroll.setVisible(true);
        HouseUtensilsScroll.setVisible(false);
        BabyNeedsScroll.setVisible(false);
        jBabyNeeds.setBackground(new java.awt.Color(255, 102, 0));
        jDrink.setBackground(new java.awt.Color(0, 153, 102));
        jSnacks.setBackground(new java.awt.Color(255, 102, 0));
        jHouseUtensils.setBackground(new java.awt.Color(255, 102, 0));
        
        jBabyNeeds.setForeground(Color.BLACK);
        jDrink.setForeground(Color.WHITE);
        jSnacks.setForeground(Color.BLACK);
        jHouseUtensils.setForeground(Color.BLACK);
    }//GEN-LAST:event_jDrinkActionPerformed

    private void jSnacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSnacksActionPerformed
        SnacksScroll.setVisible(true);
        DrinksScroll.setVisible(false);
        HouseUtensilsScroll.setVisible(false);
        BabyNeedsScroll.setVisible(false);
        jBabyNeeds.setBackground(new java.awt.Color(255, 102, 0));
        jDrink.setBackground(new java.awt.Color(255, 102, 0));
        jSnacks.setBackground(new java.awt.Color(0, 153, 102));
        jHouseUtensils.setBackground(new java.awt.Color(255, 102, 0));
        
        jBabyNeeds.setForeground(Color.BLACK);
        jDrink.setForeground(Color.BLACK);
        jSnacks.setForeground(Color.WHITE);
        jHouseUtensils.setForeground(Color.BLACK);
    }//GEN-LAST:event_jSnacksActionPerformed

    private void jHouseUtensilsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHouseUtensilsActionPerformed
        SnacksScroll.setVisible(false);
        DrinksScroll.setVisible(false);
        HouseUtensilsScroll.setVisible(true);
        BabyNeedsScroll.setVisible(false);
        jBabyNeeds.setBackground(new java.awt.Color(255, 102, 0));
        jDrink.setBackground(new java.awt.Color(255, 102, 0));
        jSnacks.setBackground(new java.awt.Color(255, 102, 0));
        jHouseUtensils.setBackground(new java.awt.Color(0, 153, 102));
        
        jBabyNeeds.setForeground(Color.BLACK);
        jDrink.setForeground(Color.BLACK);
        jSnacks.setForeground(Color.BLACK);
        jHouseUtensils.setForeground(Color.WHITE);
    }//GEN-LAST:event_jHouseUtensilsActionPerformed

    private void IMSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMSButtonActionPerformed
        POS.setVisible(false);
        IMS.setVisible(true);
        ADM.setVisible(false);
        SET.setVisible(false);
    }//GEN-LAST:event_IMSButtonActionPerformed

    private void ADMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADMButtonActionPerformed
        POS.setVisible(false);
        IMS.setVisible(false);
        ADM.setVisible(true);
        SET.setVisible(false);
    }//GEN-LAST:event_ADMButtonActionPerformed

    private void SETButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SETButtonActionPerformed
        POS.setVisible(false);
        IMS.setVisible(false);
        ADM.setVisible(false);
        SET.setVisible(true);
    }//GEN-LAST:event_SETButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ADM;
    private javax.swing.JButton ADMButton;
    private javax.swing.JPanel BabyNeedsPage;
    private javax.swing.JScrollPane BabyNeedsScroll;
    private javax.swing.JPanel Background;
    private javax.swing.JPanel DrinksPage;
    private javax.swing.JScrollPane DrinksScroll;
    private javax.swing.JPanel HouseUtensilsPage;
    private javax.swing.JScrollPane HouseUtensilsScroll;
    private javax.swing.JPanel IMS;
    private javax.swing.JButton IMSButton;
    private javax.swing.JLayeredPane MenuPanels;
    private javax.swing.JPanel POS;
    private javax.swing.JButton POSButton;
    private javax.swing.JLayeredPane ProductPanels;
    private javax.swing.JPanel SET;
    private javax.swing.JButton SETButton;
    private javax.swing.JPanel SnacksPage;
    private javax.swing.JScrollPane SnacksScroll;
    private javax.swing.JButton jBabyNeeds;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jDrink;
    private javax.swing.JButton jHouseUtensils;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jSnacks;
    // End of variables declaration//GEN-END:variables
}
